/*WAQTD maximum salary of an employee .*/

SELECT MAX( SAL ) 
FROM EMP;

/*WAQTD name of the employee getting maximum salary */
SELECT ENAME 
FROM EMP
WHERE SAL= MAX( SAL)

/*WAQTD name and salary earned by the employee getting Minimum salary*/
SELECT ENAME , SAL
FROM EMP
WHERE SAL= ( SELECT MIN( SAL) 
             FROM EMP)

/*WAQTD NAME OF THE EMPLOYEE EARNING MAXIMUM SALARY*/
SELECT ENAME 
FROM EMP
WHERE SAL = ( SELECT MAX(SAL) FROM EMP);

/*WAQTD NAME OF THE EMPLOYEE EARNING MINIMUM SALARY*/
SELECT ENAME 
FROM EMP
WHERE SAL = ( SELECT MIN(SAL) FROM EMP );

/*WAQTD NAME AND HIREDATE OF THE EMPLOYEE HIRED BEFORE
ALL THE EMPLOYEES (FIRST EMP) */
 
SELECT ENAME, HIREDATE 
FROM EMP
WHERE HIREDATE = ( SELECT MIN(HIREDATE) FROM EMP );

/*WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AT THE LAST*/
SELECT ENAME, HIREDATE 
FROM EMP
WHERE HIREDATE = ( SELECT MAX(HIREDATE) FROM EMP );

/*WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS MIN COMISSION*/
SELECT ENAME, COMM 
FROM EMP
WHERE COMM= ( SELECT MIN(COMM) FROM EMP );
