/*NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES.*/
SELECT ENAME, LOC 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO

/*WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING. */
SELECT DNAME, SAL 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND DNAME ='ACCOUNTING';

/*WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOS SALARY IS MORE THAN 2340*/ 
SELECT DNAME, SAL*12 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL > 2340
